Added proper return statuses for
pubnub/kotlin pull request #120
Opened 2023-05-02 13:14 UTC by marcin-cebo

Added proper return statuses for
HandshakeReconnectEffect and ReceiveReconnectEffect.
Added proper transitions from HandshakeFailed and ReceiveFailed

2023-05-11 11:12 UTC, kleewho requested changes

2023-05-11 13:29 UTC, marcin-cebo commented on src/main/kotlin/com/pubnub/api/subscribe/eventengine/effect/SubscribeManagedEffectFactory.kt
> +                        status.exception ?: PubNubException("dfa")
Sure, I will change it.

2023-05-11 14:02 UTC, marcin-cebo commented on src/test/kotlin/com/pubnub/api/subscribe/eventengine/effect/SubscribeManagedEffectFactoryTest.kt
> +        Thread.sleep(50)
ok

2023-05-12 11:47 UTC, kleewho approved these changes

2023-05-15 14:07 UTC, merged