Integrated Presence with PubNub stage1
pubnub/kotlin pull request #139
Opened 2023-08-12 11:40 UTC by marcin-cebo

2023-08-24 11:06 UTC, kleewho requested changes

2023-08-24 11:06 UTC, kleewho commented on src/main/kotlin/com/pubnub/api/managers/PresenceEventEngineManager.kt
> +class PresenceEventEngineManager(
This class is the same as the `SubscribeEventEngineManager`. I think we should have just one implementation

2023-08-24 11:06 UTC, kleewho commented on src/main/kotlin/com/pubnub/api/presence/eventengine/PresenceEventEngine.kt
> +class PresenceEventEngine(
Generalized EventEngine implementation should be in `c.p.a.eventengine` package and both Subscribe and Presence should use it. Both have exactly the same implementation so there's no need to duplicate it

2023-08-24 11:06 UTC, kleewho commented on src/main/kotlin/com/pubnub/api/subscribe/Subscribe.kt
> +import com.pubnub.api.presence.eventengine.event.PresenceEvent
I don't think the package `c.p.a.subscribe` should depend on `c.p.a.presence`. It make sense to use just subscribe without presence. `Subscribe` class should be concerned only with subscribe and presence related things should go into `c.p.a.presence.Presence`

2023-08-24 11:06 UTC, kleewho commented on src/main/kotlin/com/pubnub/api/subscribe/eventengine/configuration/EventEnginesConfImpl.kt
> +class EventEnginesConfImpl : EventEnginesConf {
I have proposal how we can do keep the "configurations" for both presence and subscribe more separate. I will have it in one of the commits

2023-08-24 11:06 UTC, kleewho commented on src/test/kotlin/com/pubnub/api/subscribe/SubscribeTest.kt
> +        assertEquals(PresenceEvent.Joined(setOf(channelToSubscribe), setOf(channelGroupsToSubscribe)), presenceEvent.captured)
None of the Presence things should be tested here

2023-08-30 07:57 UTC, kleewho approved these changes
It obviously looks good to me. What do you think?

2023-09-01 12:04 UTC, marcin-cebo commented on src/test/kotlin/com/pubnub/contract/subscribe/eventEngine/step/EventEngineSteps.kt
I like this refactor. I wish I could write such kotlin code.

2023-09-01 12:04 UTC, marcin-cebo commented on src/test/kotlin/com/pubnub/api/presence/PresenceTest.kt
> +                arguments(
I like test.

2023-10-19 08:40 UTC, merged