Clen 905 subscribe
pubnub/kotlin pull request #94
Opened 2022-12-22 13:05 UTC by kleewho

2023-01-02 06:19 UTC, Chesteer89 approved these changes

2023-01-02 06:19 UTC, Chesteer89 commented on src/integrationTest/kotlin/com/pubnub/api/integration/PublishIntegrationTests.kt
> +        val message = messageFuture.get(2_000, TimeUnit.MILLISECONDS)
Why the timeout is set to 2s?

2023-01-02 11:45 UTC, kleewho commented on src/integrationTest/kotlin/com/pubnub/api/integration/PublishIntegrationTests.kt
> +        val message = messageFuture.get(2_000, TimeUnit.MILLISECONDS)
🤷 I'll make it the same

2023-01-03 11:08 UTC, marcin-cebo requested changes

2023-01-03 11:08 UTC, marcin-cebo commented on src/test/kotlin/com/pubnub/api/legacy/endpoints/pubsub/SubscribeEndpointTest.kt
> +                                  "mt": "${expectedMessageType.type}",
Shouldn't it be "expectedMessageType.value" instead of "expectedMessageType.type"?

2023-01-03 12:34 UTC, kleewho commented on src/main/kotlin/com/pubnub/api/workers/SubscribeMessageProcessor.kt
>  import com.pubnub.api.PubNub
Sure

2023-01-03 12:40 UTC, marcin-cebo approved these changes

2023-01-03 13:10 UTC, merged